apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-10
spec:
  template:
    spec:
      containers:
      - name: sleep-10
        image: busybox
        command: ["sleep", "10" ] 
      restartPolicy: Never
  backoffLimit: 4
