apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-uo
spec:
  template:
    spec:
      containers:
      - name: sleep-uo
        image: busybox
        command: ["sleep", "10" ]
      restartPolicy: Never
  backoffLimit: 4    
